In [20]:
import numpy as np

In [21]:
data = np.random.randint(9, size=(3, 3))
data

array([[8, 5, 4],
       [7, 4, 0],
       [2, 3, 6]])

In [22]:
data*10


array([[80, 50, 40],
       [70, 40,  0],
       [20, 30, 60]])

In [23]:
data + data

array([[16, 10,  8],
       [14,  8,  0],
       [ 4,  6, 12]])

In [24]:
2 * data

array([[16, 10,  8],
       [14,  8,  0],
       [ 4,  6, 12]])

In [25]:
data.shape

(3, 3)

In [27]:
data = [6, 7.5, 8, 0, 1]
arr1 = np.array(data)

In [28]:
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [30]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)

In [31]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [34]:
arr2.ndim

2

In [35]:
arr2.shape

(2, 4)

In [37]:
arr1.dtype

dtype('float64')

In [38]:
arr2.dtype

dtype('int64')

In [39]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [40]:
np.zeros((3, 6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [41]:
np.empty((2, 3, 2))

array([[[  6.94327335e-310,   2.22396655e-316],
        [  0.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000]],

       [[  0.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000]]])

In [43]:
np.empty((3, 3, 3))

array([[[  6.94327335e-310,   2.21229711e-316,   6.94326618e-310],
        [  6.94324383e-310,   6.94326618e-310,   6.94327183e-310],
        [  6.94327412e-310,   6.94327412e-310,   6.94327412e-310]],

       [[  6.94327412e-310,   6.94326934e-310,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000],
        [  4.79243676e-322,   6.94327335e-310,   2.21230343e-316]],

       [[  6.94327411e-310,   3.21142670e-322,   6.94327335e-310],
        [  6.94327335e-310,   5.83403688e-302,   6.94324293e-310],
        [  6.94327410e-310,   0.00000000e+000,   1.10670705e-321]]])

In [45]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])